spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
  security:
    require-ssl: true
  servlet:
    ssl:
      key-store: file:c:/users/Kai/documents/bbw-m183-vulnerapp/selfsigned_localhost_sslserver.jks # Here we are pointing to the keystore file.
      key-store-password: passvulner
      key-store-type: JKS
      key-alias: selfsigned_localhost_sslserver
      key-password: passvulner
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    org.hibernate.SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8443
